### ISSUE TITLE
Tried to comple for with correct 16mb settings.

### ISSUE THREAD

**Issue by markeby** [nikthefix/Lilygo_Support_T_Encoder_Pro_Smart_Watch#2]
Sketch uses 2611449 bytes (199%) of program storage space. Maximum is 1310720 bytes.
Global variables use 21768 bytes (6%) of dynamic memory, leaving 305912 bytes for local variables. Maximum is 327680 bytes.
Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it.
text section exceeds available space in board

Compilation error: text section exceeds available space in board

**Comment by nikthefix** [comment]
@markeby 
Hello. Did you select 'Huge App' for the partition scheme in the build settings?

**Comment by markeby** [comment]
That did it.  I missed that setting.  Never had to use it before.
